### ISSUE TITLE
Implement record punctuation

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [NatLibFi/melinda-marc-record-utils#1]
Import the record punctuation module from https://github.com/NatLibFi/aleph-record-caretaker/blob/master/lib/marc-punctuation-fix.js:

## punctuation.js
```js
export {readRulesFromCSV, createFixer, RecordTypes, PunctuationError}
```

## Expose in index.js
```js
import {readRulesFromCSV, createFixer, RecordTypes, PunctuationError} from './punctuation';
const Punctuation = {readRulesFromCSV, createFixer, RecordTypes, PunctuationError};
export Punctuation;
```

**Comment by ammsalme** [comment]
Note: current ruleset is just a subset of punctuation rules for MARC21 fields. Implementation should make adding and editing rules easily possible.
